# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2023, daniyl-x


- name: Audit servers using Lynis
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_facts["os_family"] == "Debian"

  tasks:
    - name: Make sure the latest version of Lynis installed
      package:
        name: lynis
        state: latest

    - name: Perform Lynis scan
      command: lynis audit system

    - name: Fetch Lynis logs
      fetch:
        src: /var/log/lynis.log
        dest: "lynis-{{ ansible_host }}.log"
        flat: true

